<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQQ9Q3K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQQ9Q3K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHQQ9Q3K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHQQ9Q3K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHQQ9Q3K\App_KernelDevDebugContainer([
    'container.build_hash' => 'HQQ9Q3K',
    'container.build_id' => 'dcc45a12',
    'container.build_time' => 1707359306,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQQ9Q3K');
