<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUKmcLiO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUKmcLiO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUKmcLiO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUKmcLiO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUKmcLiO\App_KernelDevDebugContainer([
    'container.build_hash' => 'UKmcLiO',
    'container.build_id' => 'a65b99bc',
    'container.build_time' => 1707221217,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUKmcLiO');
